### PR TITLE
Updating for v0.2.0 on npm.

### PR DESCRIPTION
**Pull request by EdwinGuzman**
Once approved and merged, you should be able to publish on npm by doing `npm publish`. Since the version was updated in `package.json`, npm will automatically pick it up.

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
Just remember that the clients need to update all the `sierra-wrapper` references to `@nypl/sierra-wrapper` reference.

**Comment by jobinthomasnypl** [comment]
Will this affect current clients that are using require ('sierra-wrapper')?

**Comment by EdwinGuzman** [comment]
No. That npm module will still exist. Once this one is up and running, the existing one should be removed and all the clients should be updated.

**Comment by jobinthomasnypl** [comment]
We may not be able to remove the existing one, right? Because we have non nypl clients using that client.

**Comment by EdwinGuzman** [comment]
What non-nypl clients are using that library??

**Comment by jobinthomasnypl** [comment]
We don't know which are those non-nypl clients specifically. However, we know that there are others who have downloaded the client based on the number of the downloads that npmjs is showing.

**Comment by jobinthomasnypl** [comment]
@EdwinGuzman and I talked offline. We will deprecate 0.1.4 and encourage users to use 0.2.0

**Pull request merged**
